### ISSUE TITLE
Reading in npm http(s)-proxy when forming http(s) request

### ISSUE THREAD

**Issue by luwenlim** [akamai/AkamaiOPEN-edgegrid-node#45]
Facing intermittent (~50% of the time) ECONNRESET while hitting akamai endpoint(s):

error read ECONNRESET Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:615:25)

No logs are available on Akamai servers indicating request did not make it to endpoint during the above-mentioned instances.

I am currently behind a corporate proxy, within which I am using the http(s)-proxy for "npm install" commands. 

Proxy variable setting was done using "npm config set https-proxy http://{username}:{passphrase}@{url}:{port}"

Additionally, interested to know if current implementation has the option to force traffic over TLS 1.2 or TLS1.3 as it is a requirement for endpoints connecting to *.akamaiapis.net by October 15, 2018

**Comment by luwenlim** [comment]
Figured out how to include proxy
