### ISSUE TITLE
TypeError: this._setConfigFromStrings is not a function

### ISSUE THREAD

**Issue by mrinalsymc** [akamai/AkamaiOPEN-edgegrid-node#65]
Hi,

I am trying to initialize egdegrid using 

```
const EdgeGrid = require('edgegrid');
...
let eg = EdgeGrid(<clientToken>, <clientSecret>,< accessToken>, <CDN_INVALIDATE_URL>)
```
but i am seeing this following error.

```
[4/28/2020 1:22:07 AM] Executed 'Functions.TransformAppleSoftwareUpdateData' (Failed, Id=5e2ae32a-0c71-4223-8553-9e68e4ab45bd)
[4/28/2020 1:22:07 AM] System.Private.CoreLib: Exception while executing function: Functions.TransformAppleSoftwareUpdateData. System.Private.CoreLib: Result: Failure
[4/28/2020 1:22:07 AM] Exception: TypeError: this._setConfigFromStrings is not a function
[4/28/2020 1:22:07 AM] Stack: TypeError: this._setConfigFromStrings is not a function
[4/28/2020 1:22:07 AM]     at EdgeGrid (/Users/mrinal_khanvilkar/cb/apple-software-update-data-transformer/node_modules/edgegrid/src/api.js:30:10)
[4/28/2020 1:22:07 AM]     at invalidateCDN (/Users/mrinal_khanvilkar/cb/apple-software-update-data-transformer/TransformAppleSoftwareUpdateData/index.js:103:14)
[4/28/2020 1:22:07 AM]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[4/28/2020 1:22:07 AM]     at async module.exports (/Users/mrinal_khanvilkar/cb/apple-software-update-data-transformer/TransformAppleSoftwareUpdateData/index.js:83:13).
```

**Comment by piotrpio** [comment]
Hello @mrinalsymc 
Thanks for submitting the issue. I believe the syntax you are looking for is:
```
const EdgeGrid = require('edgegrid');
...
let eg = new EdgeGrid(<clientToken>, <clientSecret>,< accessToken>, <CDN_INVALIDATE_URL>)
```
Without the __new__ keyword, `this` will not be bound to the context of this object and thus `_setConfigFromStrings` method is not available inside edgegrid initialization function.

Please let us know if that helps.

**Comment by green3g** [comment]
I'm running into this problem when running the akamai-edgegrid package in Nesjs under a typescript project.

```
[Nest] 40463  - 12/10/2024, 4:26:38 PM   ERROR [ExceptionHandler] this._setConfigFromStrings is not a function
TypeError: this._setConfigFromStrings is not a function
    at EdgeGrid (/Users/groemhildt/projects/release-manager/node_modules/akamai-edgegrid/src/api.js:24:14)
```

Any tips for getting this project working in typescript?

I'm importing like this:

```ts
import * as EdgeGrid from 'akamai-edgegrid';
```

I've also tried several other methods, neither works:

```ts
import EdgeGrid from 'akamai-edgegrid';
import EdgeGrid = require('akamai-edgegrid');
```

**Comment by green3g** [comment]
Nevermind - this is resolved. I had a dumb typo further up in the code.
